# Generated by Django 5.0.4 on 2024-06-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
